Accumulated changes over time

diff --git a/dump b/dump
--- a/dump
+++ b/dump
@@ -2,6 +2,17 @@
 set -euo pipefail
 INPUT_TEXT="$@"
 
+if [[ -z "$INPUT_TEXT" ]]; then
+    # Check if there's only one executable
+    if [[ -z "$INPUT_TEXT" ]]; then
+        INPUT_TEXT=$(find . -maxdepth 5 -executable -type f -printf "%f\n")
+        if [[ $(echo "$INPUT_TEXT" | wc -l) -ne 1 ]]; then
+            echo "No input given and couldn't find a single executable in the current directory."
+            exit 1
+        fi
+    fi
+fi
+
 INPUT_TEXT="-Mintel $INPUT_TEXT"
 
 if [[ ! "$INPUT_TEXT" =~ "-d" ]]; then
